### ISSUE TITLE
Error with no display on linux

### ISSUE THREAD

**Issue by johnk-** [zsx/r3#1]
Hi,
I get the following error message when starting the 32bit linux version with no display.

```
XOpenDisplay failed, graphics is not supported
```

It then starts up, but if I make a simple network call like read http://rebol.com then I get a segfault.
Linux version kernel is -
 3.4.62-53.42.amzn1.i686

I can work around it be setting up xvfb which resolves he issue.
Thanks
John

**Comment by zsx** [comment]
Could you "upgrade" to the latest version? This one should have been fixed.

Thanks for reporting!

**Comment by johnk-** [comment]
Update brings down the 64 bit version, not the 32 bit one. Is there a link to the 32 bit version somewhere?
    >> upgrade
    Fetching upgrade check ...
    Script: "REBOL 3.0 Version Upgrade" Version: 2.0.0 Date: 14-Feb-2014
    Checking for updates...

```
R3 current version: 3.0.0.4.4 
It was released on: 25-Feb-2014/20:24:09 

You need to update R3.
Download new release? yes
Downloading 3.0.0.4.4 ...
Saving new version to: updates/r3-64-view-linux
Copy and rename the file as needed.
```

Thanks

**Comment by zsx** [comment]
Oops.

I updated my release script today, and it apparently broke the upgrade function. Please try again, I think I got it fixed.

**Comment by johnk-** [comment]
Looks good on the ec2 box. The upgrade script is still playing up on my laptop.

```
It was released on: 25-Feb-2014/22:14:32 
You need to update R3.
Download new release? yes
Downloading 3.0.0.4.4 ...
Cannot upgrade from web.
```

I think the connection speed out to Australia may be the cause. Is there a timeout set on the download?

Cheers, John

**Comment by zsx** [comment]
OK, you can try this link directly:
http://www.atronixengineering.com/r3/download/r3-32-view-linux (for 32-bit)
http://www.atronixengineering.com/r3/download/r3-64-view-linux (for 64-bit)

**Comment by johnk-** [comment]
The links work fine. Thanks, John
