### ISSUE TITLE
READ/string crashes

### ISSUE THREAD

**Issue by earl** [zsx/r3#13]
As reported by user "Rex" [on rebolforum](http://rebolforum.com/index.cgi?f=printtopic&permalink=Rex9-Nov-2014/7:58:05-8:00&archiveflag=new), `read/string` crashes/hangs current dev builds:

```
>> system/version 
== 3.0.91.3.1 

>> system/build 
== 22-Oct-2014/15:07:38 

>> read %umlauts.txt 
== #{C3A4C3B6C3BC} 

>> read/string %umlauts.txt 
== (R3 crashes here) 
```

On a current Linux build (from b0404207), `read/string` creates an infinite signal loop (printing `[escape]` over and over and over).

**Comment by zsx** [comment]
Confirmed and looking into it.

**Comment by earl** [comment]
That fix doesn't look correct. With this fix:

```
>> read/string %/home/earl/s/t/umlauts.txt
== "Ã¤Ã¶Ã¼"  ;; Expected: "äöü"
```

UTF-8 files are not required (nor even expected, in fact) to have a BOM.

The expected behaviour is working correctly in mainline, so this is a regression that must have been introduced since.

**Comment by earl** [comment]
The regression is introduced by 8336a45a91d9d737abba742985dc4bf330cd1f8e; later, 70c7c3a7039fab52ef61ec21e41cca17e8805600 is also incorrect.

Re 8336a45a91d9d737abba742985dc4bf330cd1f8e: `What_UTF` is expected to return 0 in cases there was no BOM. So the additional `else` branch with a `return` is problematic in these cases. Before this change, when `utf == -1` was passed into `Decode_UTF_String` the function used the BOM if present or fell back to UTF-8 otherwise. With this change, with `utf == -1` the function no longer decodes strings without a BOM. (As an aside: I'm not sure this first commit fixes any uninitiliazed variable issue; I think only the second commit does.)

Re 70c7c3a7039fab52ef61ec21e41cca17e8805600: This now changes the actual decoding calls to _only_ run when `utf != -1`, disabling the `utf == -1` BOM-based encoding detection altogether. With `bom == -1` this now no longer does any decoding at all, but only skips the BOM and then copies the remaining bytes as is.

(I'll also add the above remarks as inline comments in the respective commits; hopefully that'll make it easier to follow along :)

**Comment by earl** [comment]
I'm preparing a pull request with an improved fixed.
