### ISSUE TITLE
'enline can cause lockups (at least on Win-x64 dev version)

### ISSUE THREAD

**Issue by Respectech** [zsx/r3#16]
I tried to perform the following:

> > write/append %orders.txt enline rejoin [order-text "^/" mold order "^/"]

and Windows popped up a requester stating that r3.exe had stopped working and was going to be closed.  Tried the same script on the mainline r3.exe build (Win32), and it worked as designed.

**Comment by zsx** [comment]
It works fine on my Win7 system:

```
**************************************************************************
**                                                                      **
**  REBOL 3.0                                                           **
**                                                                      **
**    Copyright: 2012 REBOL Technologies                                **
**               All rights reserved.                                   **
**    Website:   www.REBOL.com                                          **
**                                                                      **
**    Version:   3.0.91.3.3                                             **
**    Platform:  Windows win32-x64                                      **
**    Build:     20-Nov-2014/14:06:37                                   **
**                                                                      **
**    Language:  English                                                **
**    Locale:    United States                                          **
**    Home:      X:\rebol-test.git\                                     **
**                                                                      **
**************************************************************************

SECURE is disabled

Important notes:

  * Sandbox and security are not available.
  * Direct access to TCP HTTP required (no proxies).
  * Default web browser must be available.

Special functions:

  Demo - run demo launcher (from saphirion.com)
  Help - show built-in help information
  Upgrade - check for newer releases

>> enline "a^/b^/c"
== "a^M^/b^M^/c"

>> write %test.txt enline "a^/b^/c"
>>
```

Could the error caused by the REJOIN? what's your "order-text" and "order"?

**Comment by Respectech** [comment]
I’ve reduced it to a more manageable test:

Order-text: #{
0A2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D
2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D
2D0A0A427579657220696E666F726D6174696F6E3A0A4B757274205765737365
6C696E670A6B7572747740726F616472756E6E65722E636F6D0A0A0A496E7374
72756374696F6E732066726F6D2062757965723A0A4E6F6E652070726F766964
65640A0A536869702D746F20616464726573733A202D20436F6E6669726D6564
0A4B7572742057657373656C696E670A323220526565642048496C6C2052640A
4865726D6F6E2C204D452030343430310A556E69746564205374617465730A0A
5368697070696E67206D6574686F643A0A4E6F74207370656369666965640A0A
2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D
2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D
0A5061796D656E742064657461696C730A2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D
2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D
2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D2D0A0A4465736372697074696F6E3A20
204F44524F49442D55332C0A556E69742070726963653A202436392E39352055
53440A5175616E746974793A20310A416D6F756E743A202436392E3935205553
440A200A2020200A4465736372697074696F6E3A202057694669204D6F64756C
6520332C0A556E69742070726963653A2024382E3935205553440A5175616E74
6974793A20310A416D6F756E743A2024382E3935205553440A200A2020200A44
65736372697074696F6E3A2020553320436173652C0A556E6974207072696365
3A2024332E3935205553440A5175616E746974793A20310A416D6F756E743A20
24332E3935205553440A200A2020200A537562746F74616C3A202438322E3835
205553440A5368697070696E6720616E642068616E646C696E673A2024362E30
30205553440A496E737572616E63653A204E2F410A0A546F74616C3A20243838
2E3835205553440A0A
}

Write/append %orders.txt enline order-text

**\* Here’s where R3 crashes ***

**Comment by zsx** [comment]
BTW, the latest dev binaries have this fix. Please give it a try when you have time.
