### ISSUE TITLE
"XOpenDisplay failed, graphics is not supported" when running r3-view on console-only system

### ISSUE THREAD

**Issue by Respectech** [zsx/r3#17]
I understand why the message is displayed, but I think it would be better to not display the message at all.  For instance, when only one r3 executable is on a system and it is used in an X environment and other times in a console-only environment, it would be handy to have the message not display by default.  Tried using -q and -c to turn it off, but neither worked.

**Comment by zsx** [comment]
You're right. It's a leftover from the initial development.

**Comment by zsx** [comment]
Oh, this has been commented out already in the development version. See https://github.com/zsx/r3/commit/94257256100d798b064643c0ce91a2c7e7e5fa93
