### ISSUE TITLE
Does not build on Windows 8.1 VS2015 (pre-release)

### ISSUE THREAD

**Issue by Freezerburn** [zsx/r3#21]
When attempting to build from vcbuild.bat (which has to be modified to detect VS2015 by looking for the VS140COMNTOOLS variable), there are 40 symbols that end up not being defined in the final link step:

_T_Library, _T_Routine, _PD_Struct, _T_Struct, _T_Callback, _Call_Routine, _Init_Serial_Scheme, _dtoa, _STRTOD, _Cmp_Struct, _MT_Struct, _MT_Routine, _Free_Routine, _reb_i32_add_overflow, _reb_u32_add_overflow, _reb_i64_add_overflow, _CT_Routine, _CT_Library, _CT_Callback, _CT_Struct, _Struct_To_Block, _reb_qsort, _reb_i64_sub_overflow, _reb_i64_mul_overflow, _Init_Core_Ext, _OS_Close_Window, _OS_Destroy_Graphics, _OS_Image_To_Cursor, _OS_Show_Soft_Keyboard, _OS_Get_Metrics, _OS_Init_Windows, _OS_Update_Windows, _OS_Open_Windows, _OS_Init_Graphics, _OS_Load_Cursor, _OS_Destroy_Cursor, _OS_Set_Cursor, _Dev_Serial, _WinMain

 When attempting to build from the r3.sln, VS2015 has the following errors:

Severity    Code    Description Project File    Line
Error   C1083   Cannot open source file: 'C:\Users\Vincent\Documents\dev\rebol\src\libffi\src\x86\win32.S': No such file or directory   libffi  C:\Users\Vincent\Documents\dev\rebol\make\msvc\libffi\c1    1
Error   A2088   END directive required at end of fiplai libffi  C:\Users\Vincent\Documents\dev\rebol\make\msvc\libffi\Win32\Release\win32_plain.asm 1
Error   C1083   Cannot open include file: 'ffi.h': No such file or directory    r3-view C:\Users\Vincent\Documents\dev\rebol\src\core\t-routine.c   33

**Comment by zsx** [comment]
Did you run "git sumodule init" and "git submodule update" to pull down the source of libffi?

**Comment by Freezerburn** [comment]
Sorry about the crazy lag time between your last comment and now, I've been insanely busy at work. Running the submodule commands allowed the r3 solution in VS2015 to build correctly, though vcbuild.bat still ends up with the missing symbols.

**Comment by zsx** [comment]
I have no idea about vcbuild.bat. The only reason I build it with MSVC is to debug with MSVS, so I've only tested building with MSVS.

As the title says building with MSVS, and it's building, I am closing this one.
