### ISSUE TITLE
Discrepancy between systems.r and platforms.r

### ISSUE THREAD

**Issue by asampal** [zsx/r3#22]
I tried building [metaeducation/ren-c](https://github.com/metaeducation/ren-c) (a fork of this repo with some build files incorporated from rebol/rebol) with OS_ID=0.3.02 in order to get a 64 bit Windows build. 

The preamble in the resulting executable incorrectly states:

`Platform:  Windows dec-alpha`

This led to seeing that https://github.com/zsx/r3/blob/atronix/src/boot/platforms.r and https://github.com/zsx/r3/blob/atronix/src/tools/systems.r seem to disagree on the ID for a Windows 64 bit build. How come the 64 bit exe you provide has the correct tag in the REPL if you are using OS_ID=0.3.02 to build? Is your executable produced from another source tree?

**Comment by zsx** [comment]
Fixed it by change the ID to 0.3.40 to match ren-c
