### ISSUE TITLE
Ren-C headers conversion

### ISSUE THREAD

**Issue by hostilefork** [zsx/r3#33]
Brett's got the Ren-C file headers conversion going and we'll be wanting to run it in a bit.  But I wanted to put it out there for feedback in case any modifications are requested.  Here for instance is a file nonexistent in R3-Alpha where the copyright is to Atronix:

https://github.com/codebybrett/temporary.201512-file-headers/blob/master/src/core/t-routine.c

We're moving to a different model for credits, which is basically to curb the idea that people are trying to maintain lists of names in the source file and instead put together a CREDITS.md.  What that will be like isn't set in stone, but basically it's a chance for everyone to link and say what they want to up front in the repository.  So if you and David have a way you would like it to be it's temporarily a wiki to sort that out:

https://github.com/codebybrett/temporary.201512-file-headers/wiki/Draft-CREDITS

Brett says he's going to be unavailable for a while so it will probably be > 2 weeks before the conversion runs, so there's time to get feedback...and of course it will be in the source repo, so it can change after that too...

The reason I asked for it to be a bit "heavier" with those line breaks is because I do want to have some sort of unit of divisions within the file for sections.  Again, this is not set in stone.  But once you have sections it would be weird if the header were too much "lighter" than the section is... it would be like having larger fonts further down the page for subsection headings.

The `//=/////=//` is used to avoid triggering three-slash syntax highlighting for Doxygen etc.  Also, kind of cool looking. :-)

**Comment by zsx** [comment]
This sounds OK to me. About the draft credits, I think it's better to list one's major feature/patch contributions, rather than the modification to files which can hardly be kept up to date.

**Comment by hostilefork** [comment]
Yes, the files were just names that were taken out of the .c files (for similar keeping-up-to-date reasons, but also reducing the friction of contribution).  Brett thought putting the files as a start in the wiki would let people have that information available for writing what they had to say, as that's what was "currently said"
