### ISSUE TITLE
"OneFunction" and ROUTINE!

### ISSUE THREAD

**Issue by hostilefork** [zsx/r3#34]
I wanted to give you a heads up on an impending plan, and get your input about it--based on your experiences and what directions you might have seen for the FFI.

The direction I'm moving in is to get everything under one FUNCTION! type, where the sub-behaviors are based on a couple of bits in the type-specific flags.  It's not too hard to imagine the user understanding that a "NATIVE!" is a function that perhaps when you say BODY-OF and it doesn't give anything back _(or gives some internal identifier, like an ISSUE of `#45` or something like that)_  However, ROUTINE! is a bit different.

So it got me to thinking about how it might be done another way.  This other way would be to have a single FFI-dispatch "native" which took a description of what to call and then a function frame to decode.  So for instance imagine there were no ROUTINE! but something more like a MAKE ROUTINE! that produced something like:

```
gtk-init: func [argc [integer!] argv [integer!]] [
    ffi-dispatch #[library! [...]] "gtk_init" this
]
```

I'm using `this` as a placeholder for something that would get the currently running frame, right now you can get it via binding, so imagine something morally equivalent:

```
>> gtk-init: func [argc [integer!] argv [integer!]] [probe context-of 'argc]
>> gtk-init 10 20
make frame! [
    argc: 10
    argv: 20
]
```

But to paint the rough picture, the idea would be that some structures that are built and managed on the C side would instead live directly in the body, and be associated that way.  The FRAME! very lightweight--size of a REBSER node only (2-pointers-in-size larger than a REBVAL, plus one pointer and change for overhead), and has a data pointer directly to the stack.

It seems to me that if FFI-dispatch did the frame decoding, what you'd have won't be much different than today in the invocations.  However I think a big win here could be if a lot of the MAKE-ROUTINE part of the logic of doing the prep work could be Rebol code.  If it needed to do some kind of precalculating it could even do that into a binary that could be passed along as a constant.  For that matter it could do all precalculation so the call winds up looking like:

```
gtk-init: func [argc [integer!] argv [integer!]] [
    ffi-dispatch #{73CAD0...E5F9} this
]
```

I'll have to look more into it.  But because I've only started thinking about this recently, it's not urgent.  I just thought I'd mention the direction to you now in case you had any thoughts.

**Comment by hostilefork** [comment]
I've laid some of the groundwork for this.  I'll try and put together a little demo of what it would look like to divide the labor between Rebol code and C code a bit more.

What it would likely mean is that the C dispatching code would speak at a lower level.  For instance it wouldn't know the words for the FFI language... it would expect the Rebol code to have already done all the processing from words into the numbers it wants.  _(It looks as if, for instance, the FFI_TYPE values are `#define` fixed...there's probably little risk of them changing.)_

It seems also to me that there may not need to be a type for CALLBACK!.  Callback looks to be a reaction to when a FUNCTION! is passed to something that is a ROUTINE!.  So only routines that take FUNCTION! would need to be concerned about them, and make a stub for calling them.

The issue is how these stubs are made and garbage collected...if you make them every time, it's wasteful.  So if the manufactured routine cached stubs for the functions it had seen in a small table, it might reuse and manage them that way.  Perhaps then a hook like `ffi-flush-callbacks` if you want to get rid of all the stubs.  Since you say there aren't deployment callbacks really to worry about at this point, there should be opportunity to experiment.

With the soon-to-be-debugger, it shouldn't be a nightmare to have more of the code in Rebol.  The debugger might even be really good... :-)

**Comment by zsx** [comment]
Haven't read it thoroughly yet, but I doubt callback! can be eliminated. Beside the rebol function, it also holds the information about type conversion between C and rebol. Suppose the expected c callback is like:

```
int8_t (*foo)(int16_t bar)
```

The corresponding rebol function would be:

```
foo: func [bar [integer!]][]
```

Without the type information, FFI doesn't know how to convert `bar` from C to integer! and pass return value from `foo` back to C.

**Comment by hostilefork** [comment]
I'm not suggesting the callback _mechanism_ be eliminated, rather that it be done on-demand when a Rebol function is passed to a routine.

If the only place where a callback is interesting is to C functions trying to call back into Rebol, then that C function had to get the Rebol function pointer somehow.  My suggestion is that the translation be done like other things where Rebol types are mapped into the type passed to C.

The "trick" would seem to be that you don't want to be wasteful and construct a callback every time a Rebol function is passed in an argument slot to a C function.  So this is where I was suggesting that what callback is now is a kind of "cache" of that, to keep from redoing the work.  But that caching could be moved into the routine argument fulfillment and dispatch layer, so that when it saw a Rebol function being passed it could go look to see if it was in a table, and if not make a callback and put it in the table.

**Comment by zsx** [comment]
Right, the type translation is not different than the one done for routine!. routine!/callback! holds the C data types, while interpreter holds rebol types. Eliminating callback! means losing the C data types for the translation. This piece of information gotta be saved somewhere, because a callback! can also work as a cache as you've mentioned, it seemed to me the perfect place to store that information.

**Comment by zsx** [comment]
The data types betwen C and rebol is not a 1-to-1 relationship, so the C type that a REBVAL can be translated to/from must be specified explicitly.

**Comment by hostilefork** [comment]
> The data types betwen C and rebol is not a 1-to-1 relationship, so the C type that a REBVAL can be translated to/from must be specified explicitly.

Yes, but isn't that what routine does already?  If a parameter to a routine is a function pointer, then wouldn't that function pointer have to be typed? (or shouldn't it be?)

**Comment by zsx** [comment]
> f a parameter to a routine is a function pointer, then wouldn't that function pointer have to be typed? (or shouldn't it be?)

No, routine! doesn't care about the type of the pointer.

**Comment by hostilefork** [comment]
> No, routine! doesn't care about the type of the pointer.

So you are saying you might have a routine that takes a number and an...unknown pointer argument, and if the number is 1 then the pointer argument is to a function that takes a char... and if it is 2 it means the pointer argument is to a function that takes an int.  Hmm.

I don't know how common that is.  It's probably more common with callbacks that people would want the system to figure out if the types of the function they're passing can be made to match with the callback expectations...and if so, make the right C wrapper for it.

There might be a way to design it to allow for both.  I should probably sit down with some real examples before speculating too much.

**Comment by zsx** [comment]
> So you are saying you might have a routine that takes a number and an...unknown pointer argument, and if the number is 1 then the pointer argument is to a function that takes a char... and if it is 2 it means the pointer argument is to a function that takes an int. Hmm.

This is syntactically possible, but doesn't make practical sense. Routine! is just a wrapper around the underlying C function.

Let me give you an example how callback! looks like, https://github.com/zsx/c2r3/blob/master/demos/gtk-demos/css-accordion.reb#L20 calls `gtk/container_forall` which is defined as (https://github.com/zsx/c2r3/blob/master/bindings/gtk.reb#L7878):

```
container_forall: make routine! compose/deep [[
    container [pointer]
    callback [pointer]
    callback_data [pointer]
    return: [void]
    abi: default
] (gtk) "gtk_container_forall"]
```

whose corresponding C prototype is:

```
void
gtk_container_foreach (GtkContainer *container,
                       GtkCallback callback,
                       gpointer callback_data);
```

and the callback is like (https://github.com/zsx/c2r3/blob/master/demos/gtk-demos/css-accordion.reb#L26):

```
apply-css-cb: make callback! [[
    widget [pointer]
    provider [pointer]
] :apply-css]
```

**Comment by hostilefork** [comment]
By now we have this absorbed, I think.  :)
