### ISSUE TITLE
Seg Fault with 'to-image

### ISSUE THREAD

**Issue by Respectech** [zsx/r3#6]
> > about
> > ---
> > ---
> > 
> > *\*  REBOL 3.0                                                           **
> > ---
> > 
> > *\*    Copyright: 2012 REBOL Technologies                                **
> > *\*               All rights reserved.                                   **
> > *\*    Website:   www.REBOL.com                                          **
> > ---
> > 
> > *\*    Version:   3.0.90.4.20                                            **
> > *\*    Platform:  Linux libc6-arm                                        **
> > *\*    Build:     8-Aug-2014/17:30:20                                    **
> > ---
> > 
> > *\*    Language:  English                                                **
> > *\*    Locale:    United States                                          **
> > *\*    Home:      /home/odroid/                                          **
> > ---
> > ---
> > 
> > a: view/no-wait [text "Test"] 
> > == make gob! [offset: 894x551 size: 132x21 alpha: 255 text: "REBOL: untitled"] 
> > 
> > to-image a 
> > Segmentation fault (core dumped)

**Comment by zsx** [comment]
This should be fixed. Please re-open it if it's not.
