### ISSUE TITLE
Serial not working in latest R3-armv7hf-view-linux-net-poll-serial

### ISSUE THREAD

**Issue by Respectech** [zsx/r3#7]
Here is some output from r3-serial compiled by Josh Shireman:

> > gs: open serial://ttyUSB0/57600 
> > write gs "m"  
> > print to-string read gs  
> > m
> >    ------- HARDWARE TEST MENU -- 1=on 0=off-------------

Here is the same test using the latest executable from this repo:

> > gs: open serial://ttyUSB0/57600
> > write gs "m"
> > print to-string read gs 
> > m

I always only can read the characters I sent out via serial, but no other serial data come through.  I verified that writing to serial works fine, but reading from serial appears to be broken.

**Comment by zsx** [comment]
As far as I can tell, you need to provide an "awake" function to the port. All communication is asynchronous in R3. A simple "read" could return a result of any length, or nothing at all.

Could you try this one?

``` rebol
gs: open serial://ttyUSB0/57600
written: false
gs/awake: func [evt][
     switch evt/type [
          read [
                print to-string evt/port/data
                read evt/port
                return true
          ]
          wrote [
                 written: true
                 return true
          ]
     ]
     false
]
write gs "m"
while [not written][
    wait [gs 1]
]
read gs
wait [gs 1]
```

**Comment by Respectech** [comment]
I tried your code snippet and it didn't work:

odroid@odroid:~/r3$ sudo ./r3-view test.r3

*\* Script error: port has no value
*\* Where: switch -apply- wake-up either while -apply- wait do either either either -apply-
*\* Near: switch evt/type [
    read [
        print to-string evt/por...


I checked the contents of the 'evt object, and it did contain an evt/port item, so I don't know why that error message is appearing.

-Bo

**Comment by zsx** [comment]
Sorry, I had a typo there. Could you try the new one (I just edited it)? The error is about "read port", not "evt/port", btw.
