### ISSUE TITLE
Large integer problem

### ISSUE THREAD

**Issue by Respectech** [zsx/r3#8]
> > i: 9'999'999'999'999'999'999  
> > == 9223372036854775807

Tested on Linux odroid 3.8.13.23 #1 SMP PREEMPT Sun Jul 6 04:53:31 UTC 2014 armv7l armv7l armv7l GNU/Linux

*\*    Version:   3.0.90.4.20                                            **
*\*    Platform:  Linux libc6-arm                                        **

**Comment by zsx** [comment]
I believe this is fixed by https://github.com/zsx/r3/commit/790829aa4f7613e281b4160abfe2f520aadd1b27

Please check the prebuilt binary for odroid at: http://www.atronixengineering.com/r3/downloads/r3-armv7hf-view-linux-net-poll-serial
