### ISSUE TITLE
r3-make-linux is missing

### ISSUE THREAD

**Issue by gregit** [zsx/r3#9]
r3-make-linux is a link only. misses r3-make

**Comment by zsx** [comment]
Well, this is kinda on purpose, you need to provide a prebuilt r3-make for your system. Because R3 can build on various (hardware) platforms, and one binary couldn't fit all of them, it's left out.

**Comment by gregit** [comment]
Using R2 as r3-make, I get:
*\* Script Error: This script needs View 2.100.100 or better to run correctly
*\* Near: do/args script system/script/args

Using R3 from "mainline" works.

Now I have issues with freetype2, will check at this later.

Thanks
